require("nvim.options")
require("nvim.keymaps")
require("nvim.plugins")
require("nvim.colorscheme")
require("nvim.cmp")
require("nvim.lsp")
require("nvim.telescope")
require("nvim.autopairs")
require("nvim.treesitter")
require("nvim.gitsigns")
require("nvim.comment")
require("nvim.nvim-tree")
require("nvim.bufferline")
require("nvim.lsp.null-ls")
require("nvim.leap")
require("nvim.colorizer")
require("nvim.lualine")
require("nvim.toggleterm")
require("nvim.impatient")
require("nvim.ts-autotag")

vim.cmd("highlight QuickScopePrimary guifg='#00ff00' gui=underline ctermfg=105 cterm=underline")
vim.cmd("highlight QuickScopeSecondary guifg='#ff0000' gui=underline ctermfg=81 cterm=underline")
